// docs/.vitepress/theme/components/ArchitectureMap.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useData, withBase } from "vitepress";

const enNodes = [
  {
    id: "entry",
    label: "Entry Surfaces",
    link: "/codex-from-source/chapter-02.html",
    detail:
      "The npm shim and Rust router narrow every command path before configuration and runtime work begin.",
  },
  {
    id: "protocol",
    label: "Protocol",
    link: "/codex-from-source/chapter-04.html",
    detail:
      "Submissions and events are the stable contract between clients and the agent runtime.",
  },
  {
    id: "session",
    label: "Session Runtime",
    link: "/codex-from-source/chapter-05.html",
    detail:
      "A Codex session owns configuration, history, skills, plugins, tools, and the event queue.",
  },
  {
    id: "turn",
    label: "Turn Loop",
    link: "/codex-from-source/chapter-06.html",
    detail:
      "Each user turn prepares context, samples the model, dispatches tools, records observations, and repeats.",
  },
  {
    id: "tools",
    label: "Tools",
    link: "/codex-from-source/chapter-09.html",
    detail:
      "Tool handlers describe what the model may call and how a call becomes a supervised side effect.",
  },
  {
    id: "boundary",
    label: "Approvals and Sandboxes",
    link: "/codex-from-source/chapter-12.html",
    detail:
      "Hooks, approval policy, and platform sandboxes bound risky actions before they mutate the world.",
  },
  {
    id: "extensions",
    label: "MCP and Skills",
    link: "/codex-from-source/chapter-17.html",
    detail:
      "External tools, plugins, apps, and skills extend the runtime without changing the central turn loop.",
  },
  {
    id: "surface",
    label: "User Surfaces",
    link: "/codex-from-source/chapter-14.html",
    detail:
      "The TUI and app-server consume the same event stream but present it to different kinds of clients.",
  },
];

const zhNodes = [
  {
    id: "entry",
    label: "入口接入面",
    link: "/zh/codex-from-source/chapter-02.html",
    detail:
      "npm shim 和 Rust router 会先收窄命令路径，然后才进入配置与运行时。",
  },
  {
    id: "protocol",
    label: "协议层",
    link: "/zh/codex-from-source/chapter-04.html",
    detail:
      "Submissions 和 events 是客户端与 Agent runtime 之间稳定的契约。",
  },
  {
    id: "session",
    label: "Session Runtime",
    link: "/zh/codex-from-source/chapter-05.html",
    detail:
      "一个 Codex session 拥有配置、历史、skills、plugins、tools 和 event queue。",
  },
  {
    id: "turn",
    label: "Turn Loop",
    link: "/zh/codex-from-source/chapter-06.html",
    detail:
      "一次用户 turn 会准备上下文、采样模型、分发工具、记录观察，然后决定继续或停止。",
  },
  {
    id: "tools",
    label: "工具系统",
    link: "/zh/codex-from-source/chapter-09.html",
    detail:
      "Tool handlers 描述模型能调用什么，以及一次调用如何变成受监督的副作用。",
  },
  {
    id: "boundary",
    label: "审批与沙箱",
    link: "/zh/codex-from-source/chapter-12.html",
    detail:
      "hooks、approval policy 和平台沙箱在风险动作改变世界前约束它。",
  },
  {
    id: "extensions",
    label: "MCP 与 Skills",
    link: "/zh/codex-from-source/chapter-17.html",
    detail:
      "外部工具、plugins、apps 和 skills 扩展 runtime，而不改写中心 turn loop。",
  },
  {
    id: "surface",
    label: "用户接入面",
    link: "/zh/codex-from-source/chapter-14.html",
    detail:
      "TUI 和 app-server 消费同一条 event stream，但服务不同类型的客户端。",
  },
];

const { lang } = useData();
const activeId = ref(enNodes[0].id);
const nodes = computed(() => (lang.value === "zh-CN" ? zhNodes : enNodes));
const activeNode = computed(() =>
  nodes.value.find((node) => node.id === activeId.value) ?? nodes.value[0],
);

watch(nodes, () => {
  activeId.value = "entry";
});
</script>

<template>
  <div class="architecture-map">
    <div class="architecture-map__nodes">
      <a
        v-for="node in nodes"
        :key="node.id"
        :href="withBase(node.link)"
        class="architecture-map__node"
        :class="{ 'is-active': node.id === activeId }"
        @mouseenter="activeId = node.id"
        @focus="activeId = node.id"
      >
        {{ node.label }}
      </a>
    </div>
    <div class="architecture-map__detail">
      <strong>{{ activeNode.label }}</strong>
      <p>{{ activeNode.detail }}</p>
    </div>
  </div>
</template>

// src/components/ArchitectureMap.tsx
import { useMemo, useRef, useState } from "react";
import type { MouseEvent, PointerEvent } from "react";

type Lang = "en" | "zh";

interface Props {
  lang?: Lang;
  base: string;
}

const nodes = [
  {
    id: "entry",
    label: { en: "Entry Surfaces", zh: "入口接入面" },
    href: { en: "codex-from-source/chapter-02", zh: "zh/codex-from-source/chapter-02" },
    detail: {
      en: "The npm shim and Rust router narrow every command path before configuration and runtime work begin.",
      zh: "npm shim 和 Rust router 会先收窄命令路径，然后才进入配置与运行时。",
    },
  },
  {
    id: "protocol",
    label: { en: "Protocol", zh: "协议层" },
    href: { en: "codex-from-source/chapter-04", zh: "zh/codex-from-source/chapter-04" },
    detail: {
      en: "Submissions and events are the stable contract between clients and the agent runtime.",
      zh: "Submissions 和 events 是客户端与 Agent runtime 之间稳定的契约。",
    },
  },
  {
    id: "runtime",
    label: { en: "Turn Runtime", zh: "Turn Runtime" },
    href: { en: "codex-from-source/chapter-06", zh: "zh/codex-from-source/chapter-06" },
    detail: {
      en: "Each turn resolves context, samples the model, dispatches tools, records observations, and decides whether to continue.",
      zh: "一次 turn 会解析上下文、采样模型、分发工具、记录观察，并决定是否继续。",
    },
  },
  {
    id: "tools",
    label: { en: "Tools", zh: "工具系统" },
    href: { en: "codex-from-source/chapter-09", zh: "zh/codex-from-source/chapter-09" },
    detail: {
      en: "Tool specs, routing, approvals, sandboxing, execution, and persistence turn suggestions into governed effects.",
      zh: "tool spec、routing、approval、sandbox、execution 和 persistence 把建议变成受治理的副作用。",
    },
  },
  {
    id: "clients",
    label: { en: "Clients", zh: "客户端" },
    href: { en: "codex-from-source/chapter-14", zh: "zh/codex-from-source/chapter-14" },
    detail: {
      en: "The TUI, app-server, SDKs, and remote control paths share the same runtime contract.",
      zh: "TUI、app-server、SDK 和远程控制路径共享同一个 runtime contract。",
    },
  },
  {
    id: "extensions",
    label: { en: "Extensions", zh: "扩展" },
    href: { en: "codex-from-source/chapter-17", zh: "zh/codex-from-source/chapter-17" },
    detail: {
      en: "MCP, skills, plugins, connectors, and typed extensions add capability through explicit trust planes.",
      zh: "MCP、skills、plugins、connectors 和 typed extensions 通过显式信任平面增加能力。",
    },
  },
];

export default function ArchitectureMap({ lang = "en", base }: Props) {
  const [active, setActive] = useState(nodes[0].id);
  const touchTarget = useRef<string | null>(null);
  const activeNode = useMemo(
    () => nodes.find((node) => node.id === active) ?? nodes[0],
    [active],
  );
  const normalizedBase = base.endsWith("/") ? base : `${base}/`;

  function hasCoarsePointer() {
    return window.matchMedia("(pointer: coarse)").matches;
  }

  function previewOnPointer(
    event: PointerEvent<HTMLAnchorElement>,
    nodeId: string,
  ) {
    if (event.pointerType !== "touch") {
      setActive(nodeId);
    }
  }

  function rememberPointer(
    event: PointerEvent<HTMLAnchorElement>,
    nodeId: string,
  ) {
    touchTarget.current = event.pointerType === "touch" ? nodeId : null;
  }

  function previewOnFocus(nodeId: string) {
    if (!touchTarget.current && !hasCoarsePointer()) {
      setActive(nodeId);
    }
  }

  function previewOnTouch(
    event: MouseEvent<HTMLAnchorElement>,
    nodeId: string,
  ) {
    const fromTouch = touchTarget.current === nodeId || hasCoarsePointer();
    touchTarget.current = null;

    if (!fromTouch || nodeId === active) {
      return;
    }
    event.preventDefault();
    setActive(nodeId);
  }

  return (
    <div className="architecture-map" aria-label="Architecture map">
      <div className="architecture-map__nodes">
        {nodes.map((node) => (
          <a
            key={node.id}
            href={`${normalizedBase}${node.href[lang]}.html`}
            className={`architecture-map__node ${node.id === active ? "is-active" : ""}`}
            aria-current={node.id === active ? "true" : undefined}
            onPointerEnter={(event) => previewOnPointer(event, node.id)}
            onPointerDown={(event) => rememberPointer(event, node.id)}
            onFocus={() => previewOnFocus(node.id)}
            onClick={(event) => previewOnTouch(event, node.id)}
          >
            {node.label[lang]}
          </a>
        ))}
      </div>
      <div className="architecture-map__detail">
        <strong>{activeNode.label[lang]}</strong>
        <p>{activeNode.detail[lang]}</p>
      </div>
    </div>
  );
}
